version: '3.7'
services:
    app:
        build: .
        container_name: "app"
        volumes:
          - ./:/var/www/
          - /var/www/vendor/
        links:
          - mysql
        depends_on:
          - mysql
        ports:
          - 9000:9000
        env_file:
          - panopticon.env
        command: sh run-dev.sh
    mysql:
        image: mysql:latest
        container_name: "mysql"
        command: --default-authentication-plugin=mysql_native_password
        volumes:
          - 'dbdata:/var/lib/mysql'
        ports:
          - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: forge
            MYSQL_USER: forge
            MYSQL_PASSWORD: example
    adminer:
        image: adminer
        restart: always
        ports:
          - 8888:8080
volumes:
  dbdata:
