version: '3.7'
services:
    backend:
        build: .
        container_name: "backend"
        volumes:
          - ./:/var/www/
          - /var/www/vendor/
        links:
          - mysql
        depends_on:
          - mysql
        ports:
          - 9000:9000
    frontend:
        build: .
        container_name: "frontend"
        volumes:
          - ./:/var/www/
          - /var/www/node_modules/
        links:
          - backend
        depends_on:
          - backend
        ports:
          - 8000:8000
        command: npm run serve
    mysql:
        image: mysql
        container_name: "mysql"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
    adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080
