version: '3.7'
services:
    app:
        build: .
        container_name: "app"
        volumes:
          - ./:/var/www/
          - /var/www/vendor/
        links:
          - mysql
        depends_on:
          - mysql
        ports:
          - 9000:9000
        environment:
            APP_DEBUG: 'true'
            APP_KEY: 'base64:YxYquQaT2orH6SXcSyoQzWidSP3iVXe98DYU/7MBECg='
            APP_ENV: 'dev'
            DB_USERNAME: root
            DB_PASSWORD: example
            DB_HOST: mysql
            WAIT_HOSTS: mysql:3306
    sync-data:
        build: .
        container_name: "sync-data"
        volumes:
          - ./:/var/www/
          - /var/www/vendor/
        links:
          - mysql
          - app
        depends_on:
          - mysql
          - app
        ports:
          - 9000:9000
        command: ''
        environment:
            APP_DEBUG: 'true'
            APP_KEY: 'base64:YxYquQaT2orH6SXcSyoQzWidSP3iVXe98DYU/7MBECg='
            APP_ENV: 'dev'
            DB_USERNAME: root
            DB_PASSWORD: example
            DB_HOST: mysql
            WAIT_HOSTS: mysql:3306
    mysql:
        image: mysql
        container_name: "mysql"
        restart: always
        volumes:
          - 'dbdata:/var/lib/mysql'
        ports:
          - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: forge
    adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080
volumes:
  dbdata:
